-- Closed Funnel, per-day, full 27 stages -- for the date-picker view in the dashboard.
-- Same CASE-based single-pass structure as open_funnel_by_day_query.sql (26-way UNION ALL
-- re-scans the base data once per branch and times out over multi-day ranges -- see gotchas.md).
-- Substitute {{START_DATE}} / {{END_DATE}}.
WITH day_rows AS (
    SELECT
        history_custid AS custid,
        history_tostate AS tostate,
        history_solutiontypelevel2 AS soltype,
        CAST(DATE(history_timestamp + INTERVAL '5' HOUR + INTERVAL '30' MINUTE) AS DATE) AS activity_date
    FROM hive.workflow_nexus.lead_history_snapshot_v3
    WHERE dl_last_updated IS NOT NULL
      AND DATE(history_timestamp + INTERVAL '5' HOUR + INTERVAL '30' MINUTE) BETWEEN {{START_DATE}} AND {{END_DATE}}
      AND history_solutiontypelevel2 NOT IN ('LAN_DEACTIVATION','EMI','PO_VKYC','PO_ADD_BANK','LIMIT_UPGRADE','PO_SURPLUS_REFUND')
      AND CAST(DATE(createdtime + INTERVAL '5' HOUR + INTERVAL '30' MINUTE) AS DATE) BETWEEN {{START_DATE}} AND {{END_DATE}}
      AND history_tostate IN (
        'BASIC_DETAILS_CAPTURED','LEAD_NOT_PRESENT','BASIC_DETAILS_CAPTURED_MARKETPLACE',
        'BRE_REQUESTED','BRE_SKIPPED_MARKETPLACE','OFFERS_SHOWN_PQ','BRE_COMPLETED',
        'CHILD_LEAD_ACTIVE','LENDER_PAN_VALIDATION_SUCCESS','AADHAAR_OTP_INITIATED',
        'KYC_VALIDATION_IN_PROGRESS','KYC_VALIDATION_SUCCESS',
        'KYC_PINCODE_SERVICEABILITY_CHECK_SUCCESS',
        'SELFIE_REQUIRED','SELFIE_CAPTURED','SELFIE_CAPTURED_V3',
        'LENDER_FACE_SIMILARITY_CHECK_SUCCESS','ADDITIONAL_DATA_CAPTURED',
        'LENDER_BRE_INITIATED','LENDER_BRE_SUCCESS','LENDER_BRE_APPROVE_SUCCESS',
        'CREDIT_LINE_OFFER_REVIEW','CREDIT_LINE_OFFER_ACCEPTED',
        'EMANDATE_REQUIRED','MANDATE_SUCCESS',
        'REVIEW_OFFER_REQUIRED','REVIEW_OFFER_ACCEPTED',
        'ESIGN_REQUIRED','ESIGN_SUCCESS',
        'LMS_ONBOARDING_COMPLETED','LEAD_SUCCESSFULLY_CLOSED'
      )
),
flagged AS (
    SELECT *,
        MAX(CASE WHEN soltype IN ('CHILD_V1','CHILD_V2')
                   OR tostate IN ('BASIC_DETAILS_CAPTURED_MARKETPLACE','BRE_SKIPPED_MARKETPLACE','OFFERS_SHOWN_PQ','CHILD_LEAD_ACTIVE')
                  THEN 1 ELSE 0 END) OVER (PARTITION BY custid, activity_date) AS is_marketplace
    FROM day_rows
),
primary_tagged AS (
    SELECT custid, is_marketplace, activity_date,
      CASE tostate
        WHEN 'BASIC_DETAILS_CAPTURED' THEN '01_LEAD_CREATED'
        WHEN 'LEAD_NOT_PRESENT' THEN '01_LEAD_CREATED'
        WHEN 'BASIC_DETAILS_CAPTURED_MARKETPLACE' THEN '01_LEAD_CREATED'
        WHEN 'BRE_REQUESTED' THEN '02_BRE1_REQUESTED'
        WHEN 'BRE_SKIPPED_MARKETPLACE' THEN '02_BRE1_REQUESTED'
        WHEN 'OFFERS_SHOWN_PQ' THEN '02_BRE1_REQUESTED'
        WHEN 'BRE_COMPLETED' THEN '03_BRE1_SUCCESS'
        WHEN 'CHILD_LEAD_ACTIVE' THEN '04_MARKETPLACE_OFFER_SELECTED'
        WHEN 'LENDER_PAN_VALIDATION_SUCCESS' THEN '05_LENDER_PAN_VALIDATION_SUCCESS'
        WHEN 'AADHAAR_OTP_INITIATED' THEN '06_AADHAAR_OTP'
        WHEN 'KYC_VALIDATION_IN_PROGRESS' THEN '07_KYC_IN_PROGRESS'
        WHEN 'KYC_VALIDATION_SUCCESS' THEN '08_KYC_SUCCESS'
        WHEN 'KYC_PINCODE_SERVICEABILITY_CHECK_SUCCESS' THEN '09_KYC_PINCODE_SUCCESS'
        WHEN 'SELFIE_REQUIRED' THEN '10_SELFIE_REQUIRED'
        WHEN 'SELFIE_CAPTURED' THEN '11_SELFIE_UPLOADED'
        WHEN 'SELFIE_CAPTURED_V3' THEN '11_SELFIE_UPLOADED'
        WHEN 'LENDER_FACE_SIMILARITY_CHECK_SUCCESS' THEN '12_LENDER_FACE_SIMILARITY_CHECK_SUCCESS'
        WHEN 'ADDITIONAL_DATA_CAPTURED' THEN '13_ADDITIONAL_DATA_CAPTURED'
        WHEN 'LENDER_BRE_INITIATED' THEN '14_LENDER_BRE_REQUIRED'
        WHEN 'LENDER_BRE_SUCCESS' THEN '15_LENDER_BRE_SUCCESS'
        WHEN 'LENDER_BRE_APPROVE_SUCCESS' THEN '16_LENDER_BRE_APPROVED'
        WHEN 'CREDIT_LINE_OFFER_REVIEW' THEN '17_CREDIT_LINE_OFFER_REVIEW'
        WHEN 'CREDIT_LINE_OFFER_ACCEPTED' THEN '18_CREDIT_LINE_OFFER_ACCEPTED'
        WHEN 'EMANDATE_REQUIRED' THEN '19_EMANDATE_REQUIRED'
        WHEN 'MANDATE_SUCCESS' THEN '20_MANDATE_SUCCESS'
        WHEN 'REVIEW_OFFER_REQUIRED' THEN '21_REVIEW_OFFER_REQUIRED'
        WHEN 'REVIEW_OFFER_ACCEPTED' THEN '22_REVIEW_OFFER_ACCEPTED'
        WHEN 'ESIGN_REQUIRED' THEN '23_ESIGN_REQUIRED'
        WHEN 'ESIGN_SUCCESS' THEN '24_ESIGN_SUCCESS'
        WHEN 'LMS_ONBOARDING_COMPLETED' THEN '25_LMS_ONBOARDING_COMPLETED'
        WHEN 'LEAD_SUCCESSFULLY_CLOSED' THEN '26_SIGNED_UP'
      END AS funnel_step
    FROM flagged
),
secondary_tagged AS (
    SELECT custid, is_marketplace, activity_date,
      CASE tostate
        WHEN 'BRE_SKIPPED_MARKETPLACE' THEN '03_BRE1_SUCCESS'
        WHEN 'OFFERS_SHOWN_PQ' THEN '03_BRE1_SUCCESS'
        WHEN 'BRE_COMPLETED' THEN '04_MARKETPLACE_OFFER_SELECTED'
      END AS funnel_step
    FROM flagged
    WHERE tostate IN ('BRE_SKIPPED_MARKETPLACE','OFFERS_SHOWN_PQ','BRE_COMPLETED')
),
all_tagged AS (
    SELECT * FROM primary_tagged
    UNION ALL
    SELECT * FROM secondary_tagged
),
dedup AS ( SELECT DISTINCT activity_date, funnel_step, is_marketplace, custid FROM all_tagged WHERE funnel_step IS NOT NULL )
SELECT activity_date, funnel_step, CASE WHEN is_marketplace=1 THEN 'MARKETPLACE' ELSE 'NON_MARKETPLACE' END AS cohort, COUNT(DISTINCT custid) AS customers
FROM dedup GROUP BY activity_date, funnel_step, is_marketplace
UNION ALL
SELECT activity_date, funnel_step, 'OVERALL' AS cohort, COUNT(DISTINCT custid) AS customers
FROM dedup GROUP BY activity_date, funnel_step
ORDER BY activity_date, cohort, funnel_step
